### ISSUE TITLE
Docker run failed with exit code 1

### ISSUE THREAD

**Issue by gxyz** [shalzz/zola-deploy-action#1]
Hi, I use this action to deploy my zola project, but something was wrong.

```
 shalzz/zola-deploy-action2s
##[error]Docker run failed with exit code 1
Run shalzz/zola-deploy-action@master
/usr/bin/docker run --name dd9e73cd6edb889eab4a5fb3f12d842d35afc6_d29fdd --label dd9e73 --workdir /github/workspace --rm -e PAGES_BRANCH -e TOKEN -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/gxyz.github.io/gxyz.github.io":"/github/workspace" dd9e73:cd6edb889eab4a5fb3f12d842d35afc6
Set the GITHUB_TOKEN env variable.
##[error]Docker run failed with exit code 1
```

**Comment by shalzz** [comment]
Hi,

The action requires an access token to do most of what it does. Can you make sure you have atleast `GITHUB_TOKEN` secret set in your project settings.
Ideally it should be a Personal Access Token set to `TOKEN` so that the action also triggers a github pages refresh.

**Comment by rafaellehmkuhl** [comment]
I also had this problem, and I think a lot of people probably does.
Would you accept a PR adding this to the Usage documentation?

**Comment by shalzz** [comment]
Hi, most of what I have said in the comment is already in the README. If there is anything more you want to add, other than just adding the whole error message, then please go ahead with a pr
