### ISSUE TITLE
Possibility of using GITHUB_TOKEN for deploys?

### ISSUE THREAD

**Issue by Walther** [shalzz/zola-deploy-action#10]
Hi!

Would it be possible to integrate support for using `GITHUB_TOKEN` for deploying as an alternative to using personal access tokens?

I noticed that e.g. [this action](https://github.com/peaceiris/actions-gh-pages#github-actions-for-github-pages) seems to say that `GITHUB_TOKEN`s _can_ be used for `gh-pages` deployments, wonder if a similar approach could be added here?

Thanks!

**Comment by shalzz** [comment]
Hi, 

This action already supports using `GITHUB_TOKEN` if you do not create the `TOKEN` secret in your repo.
You can try using `GITHUB_TOKEN` but last time I tried that only updated your branch and not rebuild /publish the Github page.
