### ISSUE TITLE
Support an option for selecting Zola version

### ISSUE THREAD

**Issue by dreamer** [shalzz/zola-deploy-action#11]
In some cases, users might prefer to use the older Zola version (for whatever reason), instead of relying on the version hardcoded by the action implementation.

In my case, I would prefer to use Zola 0.10.1 to use exactly the same version as provided by my OS. This way I would be able to control when I want to upgrade my site to the next Zola release.

Prompted by: https://github.com/getzola/zola/issues/1076

**Comment by shalzz** [comment]
Hi, 

The versions of the action itself are tagged and released to match zola versions. You can find the list of zola versions here: https://github.com/shalzz/zola-deploy-action/tree/v0.10.1
