### ISSUE TITLE
fatal: could not read Password for 'https://***@github.com': No such device or address

### ISSUE THREAD

**Issue by naps62** [shalzz/zola-deploy-action#13]
I was having this error when setting up my website (https://github.com/naps62/naps62.github.io)

In my previous setup, with gatsby, I had this:

```sh
git remote set-url origin https://naps62:${{ secrets.GITHUB_TOKEN }}@github.com/naps62/naps62.github.io
```

notice that I'm using `naps62:TOKEN` instead of just `TOKEN`
As a hotfix to make this action work, I added `naps62:` as a prefix to the secret string.

Is this something I'm missing, like a permission on the token itself? or is it a bug with how this action uses the token?

**Comment by iEverX** [comment]
this maybe help
```yaml
TOKEN: $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}
```

**Comment by trojkat** [comment]
Why this is still not fixed in the documentation?
