### ISSUE TITLE
Run `zola check` in Action

### ISSUE THREAD

**Issue by vbrandl** [shalzz/zola-deploy-action#19]
It would be cool to be able to run `zola check` maybe even as a separate step in the pipeline.

This way, you could detect dead links and so on before deploying them.

**Comment by SkypLabs** [comment]
I submitted a PR to address this issue: https://github.com/shalzz/zola-deploy-action/pull/39.

**Comment by SkypLabs** [comment]
PR merged :partying_face: 

@shalzz I think this issue can be closed now.

**Comment by shalzz** [comment]
fixed by #39
