### ISSUE TITLE
Allow for enterprise URL support

### ISSUE THREAD

**Issue by kathleenfrench** [shalzz/zola-deploy-action#20]
Currently, if this action runs on a self-hosted Github instance that has a different hostname than `github.com`, the deployment will fail given the [following line](https://github.com/shalzz/zola-deploy-action/blob/d74c86d3222b4aaf555f33ce7e17b8839628e0d5/entrypoint.sh#L51) in `entrypoint.sh`

```
remote_repo="https://${GITHUB_TOKEN}@github.com/${TARGET_REPOSITORY}.git"
```

Would you be open to a PR adding the hostname as a parameter on the action so it can be compatible w/ self-hosted/enterprise environments. Something like:

```
remote_repo="https://${GITHUB_TOKEN}@${GITHUB_HOSTNAME}/${TARGET_REPOSITORY}.git"
```

Happy to do it if this sounds of interest!

**Comment by shalzz** [comment]
Hi,

Yeah this seems like a valid addition.
Is the `GITHUB_HOSTNAME` automatically set by the github runner for every job run and defaults to "github.com"? If not please set the default in the script manually if the variable is not being overridden, if your planning to create a PR.
