### ISSUE TITLE
Let's add CUSTOM_DOMAIN parameter

### ISSUE THREAD

**Issue by leotsarev** [shalzz/zola-deploy-action#24]
I propose adding CUSTOM_DOMAIN env variable that will be automatically written to static/CNAME.
It's more logical to configure it in one place than using CNAME file for custom domain and env. variables for all other settings

**Comment by shalzz** [comment]
Publishing a site via Github pages is a primarily git focused workflow so swapping out one config format for another doesn't have any benefits.
Its even worse as:
* Having a CNAME file is a github pages requirement and not just this actions requirement and helps keep the repos portable
* It complicates a setup with no clear upside
* It breaks backwards compatibility

**Comment by leotsarev** [comment]
Ok, thanks for answer!

P.S. By the way — sincere thanks for this project.
