### ISSUE TITLE
Action causes custom url in github pages to reset

### ISSUE THREAD

**Issue by tqwewe** [shalzz/zola-deploy-action#45]
Every time the zola-deploy-action runs, my Github pages custom domain is reset in the settings, and I have to manually enter the domain again and click save.

Is there any options for resolve this?

**Comment by tqwewe** [comment]
It seems like the solution is to place a file called `CNAME` into the `static` folder of the zola project. CNAME should contain the domain name (without `http://`).

**Comment by shalzz** [comment]
Yes, which is exactly what is mentioned in the readme here: https://github.com/shalzz/zola-deploy-action#custom-domain

**Comment by tqwewe** [comment]
Ah somehow i missed that 🤦‍♂️ my mistake
