### ISSUE TITLE
Latest commit breaks building without flags

### ISSUE THREAD

**Issue by Zegnat** [shalzz/zola-deploy-action#5]
The latest changes in https://github.com/shalzz/zola-deploy-action/commit/453548fdc4c1424fa891cb74c1264e63850dbf86 add double quotes around build flags. This will break Zola when no build flags are defined:

```
$ zola build ""
error: Found argument '' which wasn't expected, or isn't valid in this context
```

As the default instructions for running this action pin it to the latest commit in the master branch, this temporarily broke my deployment. (I pinned it to the previous commit now instead.)

**Comment by Folyd** [comment]
Same problem.

**Comment by shalzz** [comment]
I see, sorry about that. But yes generally you should not be using the latest commit of the action. I have tagged releases with every new release of zola.
Maybe I'll try and do development on a different branch and then push to master when everything is stable.

**Comment by Folyd** [comment]
Well, it seems like the latest release **v0.9.0** isn't including the `BUILD_DIR` env option?

**Comment by Zegnat** [comment]
> But yes generally you should not be using the latest commit of the action. I have tagged releases with every new release of zola.

Yeah, I think I originally went off of your README, which pins to using the latest master. Obviously my mistake. Though an easy one to make for people copy pasting.

I also understand the reason for following Zola’s release versioning with your tagged releases, but as @Folyd points out, this means people cannot make use of new features added to the action until a new Zola release is made. That doesn’t really have a clear-cut solution, of course.
