### ISSUE TITLE
dubious ownership error

### ISSUE THREAD

**Issue by tieje** [shalzz/zola-deploy-action#53]
Probably related to the fix for [#52](https://github.com/shalzz/zola-deploy-action/pull/52)

In my github actions, I'm getting the following error

```
Starting deploy...
Fetching themes
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
```

Not sure how to fix it. I've tried setting `set-safe-directory: '*'` but that doesn't seem to work.

**Comment by Syst3mz** [comment]
I also have this error, and adding my own line to the action to run the command first did not fix it

**Comment by Syst3mz** [comment]
Works for me, Thanks!

**Comment by tieje** [comment]
> I just tested it and it fixes the error: [blackheaven/blackheaven.github.io@4e4945a](https://github.com/blackheaven/blackheaven.github.io/commit/4e4945ae50579b07a4a183a54f6ec5c3dfe7529d)
> 
> It deserves a new tag.

It works because it refers to an older commit prior to the [#52](https://github.com/shalzz/zola-deploy-action/pull/52) . We'll still be using an old commit until this gets fixed. @shalzz , perhaps you may want to bump up the version to 16.2 at least for now.

**Comment by shalzz** [comment]
Hi, yes.
You need to use the latest commit either via the sha hash or via the master branch tag (`uses: shalzz/zola-deploy-action@master`)
I'll spin up another tag as well since this is hot fix release.
