### ISSUE TITLE
Theme is not a git repository

### ISSUE THREAD

**Issue by tostaylo** [shalzz/zola-deploy-action#6]
I am using the Sam theme for my Zola project. I added the theme to my project with 
```
git submodule add https://github.com/janbaudisch/zola-sam.git themes/sam
```
However, I am receiving the following error.
```
Starting deploy...
Fetching themes
fatal: Not a git repository (or any parent up to mount point /github/workspace)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
##[error]Docker run failed with exit code 128
```

Here is my .yaml 
```name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Zola Deploy to Pages
      uses: shalzz/zola-deploy-action@v0.9.0
    env:
        TOKEN: ${{ secrets.Token }}
```

Any thoughts?

**Comment by shalzz** [comment]
Hi,

You are missing one crucial step in your workflow. Before doing anything in github actions you have to checkout your git repo with ` - uses: actions/checkout@master`.
See the example in the README for more details.

**Comment by tostaylo** [comment]
Guess I should read the docs better. Thank you. Please delete this from the internet so the world will not see my mistake. :)

**Comment by shalzz** [comment]
No worries @tostaylo, happens to all of us.
