### ISSUE TITLE
dubious ownership error in v0.17.2

### ISSUE THREAD

**Issue by port19x** [shalzz/zola-deploy-action#73]
![2023-04-09_11-51](https://user-images.githubusercontent.com/82055622/230766135-b706bb4a-5748-41ed-8e1a-70ca0c342a2a.png)

Rolling back to 0.16.1-1 for now :/

**Comment by shalzz** [comment]
Can you check with the latest commit by using this in you action workflow? :
`uses: shalzz/zola-deploy-action@master`

**Comment by port19x** [comment]
Works :+1:
