### ISSUE TITLE
File not found when building site

### ISSUE THREAD

**Issue by Arzte** [shalzz/zola-deploy-action#76]
I appear to be getting the same error mentioned in #72, however running `zola build` locally succeeds as expected.

The error I'm getting in my builds is linked here:
https://github.com/Arzte/arzte.github.io/actions/runs/4809565754/jobs/8989876614#step:4:33

The workflow file I'm using is here:
https://github.com/Arzte/arzte.github.io/blob/main/.github/workflows/main.yml

Let me know if there's any additional information I could provide to help resolve this.

**Comment by human-errxor** [comment]
I'm getting this too. Any luck?

**Comment by samueloph** [comment]
@Arzte I've got the same issue with a failure to parse "templates/" and I've solved that with `ln -s themes/abridge/templates ./` (a symlink on `templates/`).

I'm now getting a different error but I think it's unrelated to this.

PS.: Looks like your main.yml has also changed from the documented one, in case you want to retry:
https://www.getzola.org/documentation/deployment/github-pages/

**Comment by pcwizz** [comment]
Just solve the a same issue using a symlink

**Comment by kekonn** [comment]
> @Arzte I've got the same issue with a failure to parse "templates/" and I've solved that with `ln -s themes/abridge/templates ./` (a symlink on `templates/`).
> 
> I'm now getting a different error but I think it's unrelated to this. edit - I've got a successful run after doing the symlink and then setting write permissions to the workflow, as described in [ad-m/github-push-action#96 (comment)](https://github.com/ad-m/github-push-action/issues/96#issuecomment-889984928).
> 
> PS.: Looks like your main.yml has also changed from the documented one, in case you want to retry: https://www.getzola.org/documentation/deployment/github-pages/

I am still getting this issue, but I am on windows, so symlinks are not an option for me. How would I go about and fix this?
