### ISSUE TITLE
Error in CI connected possibly to safe directories

### ISSUE THREAD

**Issue by apirogov** [shalzz/zola-deploy-action#78]
I get:

```
Run shalzz/zola-deploy-action@v0.17.2
  env:
    BUILD_DIR: .
    PAGES_BRANCH: main
    GITHUB_TOKEN: ***
    REPOSITORY: apirogov/apirogov.github.io
/usr/bin/docker run --name c9a4a598e4a64f5f8c4c0ea647e7d47c92e22d_2ae025 --label c9a4a5 --workdir /github/workspace --rm -e "BUILD_DIR" -e "PAGES_BRANCH" -e "GITHUB_TOKEN" -e "REPOSITORY" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/website-source/website-source":"/github/workspace" c9a4a5:98e4a64f5f8c4c0ea647e7d47c92e22d
Starting deploy...
Building in . directory
error: wrong number of arguments, should be 2
Set safe directories
usage: git config [<options>]
...
```

The lastest release possibly has a typo in the path that was added or the wildcard is not working correctly?

With the previous version I have no issues.

**Comment by ideasfoundry** [comment]
Facing exactly same issue.

`Run shalzz/zola-deploy-action@v0.17.2
/usr/bin/docker run --name bedb4abbd303d731c4a09be527df3df2c54a8_4f237e --label 5bedb4 --workdir /github/workspace --rm -e "PAGES_BRANCH" -e "TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/newblog/newblog":"/github/workspace" 5bedb4:abbd303d731c4a09be527df3df2c54a8
Starting deploy...
Building in . directory
Set safe directories
error: wrong number of arguments, should be 2
usage: git config [<options>]`

**Comment by pl4g** [comment]
Having the same issue, I outdated my actions to use v0.17.1 and now it works.

**Comment by nurulmac11** [comment]
> Having the same issue, I outdated my actions to use v0.17.1 and now it works.

this didnt work for me I created a new pr, now it works;
https://github.com/nurulmac11/zola-deploy-action

**Comment by prrao87** [comment]
Switching to the older version worked, but why is it that the latest version doesn't? I get the same issue at the exact same point every time:

```
Starting deploy...
Building in . directory
Set safe directories
error: wrong number of arguments, should be 2
usage: git config [<options>]
```

**Comment by shalzz** [comment]
Fixed by the latest commits and release
