### ISSUE TITLE
Problems with relative references in `load_data` function.

### ISSUE THREAD

**Issue by humb1t** [shalzz/zola-deploy-action#8]
I use `load_data` function to access file from `static` folder of my repository (and build directory for Github actions). Everything was fine for TravisCI. 
https://github.com/SamaraITCommunity/site/actions/runs/76490257

Looks like Docker runner fails to retrieve right path when compiles templates during zola build.
Will try to find a root cause and submit a PR, but maybe I missed something and there is no problem in `zola-deploy-action`.

**Comment by shalzz** [comment]
Closing this issue. If it's still an issue and you are sure it's related to the action please reopen the issue.
