### ISSUE TITLE
Release v0.17.3 with the latest fixes?

### ISSUE THREAD

**Issue by prrao87** [shalzz/zola-deploy-action#81]
I think it's worth making a release `v0.17.3` with the latest fix for the dreaded error described in #72.
**The latest version on `master` seems to address all issues**, and this is summarized below.

1. The `'*'` signs pointing to the `sass` and `themes` directories are not playing well with the `Set safe directories` portion of the pipeline
2. #72 attempted to fix this, and it was tested by multiple people (and worked)
3. [This comment](https://github.com/shalzz/zola-deploy-action/pull/72#issuecomment-1573027985) confirms that the fix worked on repos with git submodules
4. Multiple others (including myself) have confirmed that the latest version on `master` works for relatively complex sites that depend on sass, but not git submodules.

All in all, I think the fix on `master` should be released as a version so that folks can make the choice if they want to continue using `v0.17.2` (which didn't work for a lot of us), or `v0.17.3`, which works for others. Pinning the version number makes a lot more sense than using `shalzz/zola-deploy-action@master` in the longer term.

Thanks for all the work on this btw!

**Comment by shalzz** [comment]
I just released a `v0.17.2-1` hotfix release to include the git safe directories fix. Thanks!
